<?php

use Innocode\WPConfig\Env;

define( 'AWS_LAMBDA_CRITICAL_CSS_KEY', Env::get( 'AWS_LAMBDA_CRITICAL_CSS_KEY' ) );
define( 'AWS_LAMBDA_CRITICAL_CSS_SECRET', Env::get( 'AWS_LAMBDA_CRITICAL_CSS_SECRET' ) );
define( 'AWS_LAMBDA_CRITICAL_CSS_REGION', Env::get( 'AWS_LAMBDA_CRITICAL_CSS_REGION' ) );

if ( Env::get( 'AWS_LAMBDA_CRITICAL_CSS_FUNCTION' ) ) {
	define( 'AWS_LAMBDA_CRITICAL_CSS_FUNCTION', Env::get( 'AWS_LAMBDA_CRITICAL_CSS_FUNCTION' ) );
}
