<?php

use Innocode\WPConfig\Env;

define( 'AWS_LAMBDA_PRERENDER_KEY', Env::get( 'AWS_LAMBDA_PRERENDER_KEY' ) );
define( 'AWS_LAMBDA_PRERENDER_SECRET', Env::get( 'AWS_LAMBDA_PRERENDER_SECRET' ) );
define( 'AWS_LAMBDA_PRERENDER_REGION', Env::get( 'AWS_LAMBDA_PRERENDER_REGION' ) );

if ( Env::get( 'AWS_LAMBDA_PRERENDER_FUNCTION' ) ) {
	define( 'AWS_LAMBDA_PRERENDER_FUNCTION', Env::get( 'AWS_LAMBDA_PRERENDER_FUNCTION' ) );
}
