name: Update Dependencies at 06:00 on every 15th day-of-month.

on:
  schedule:
    - cron: "0 6 */15 * *"
  push:
    branches:
      - feature/update_automation

env:
  COMPOSER_CONFIG: $GITHUB_WORKSPACE/config.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Config Composer
        run: |
          echo "{" > ${{ env.COMPOSER_CONFIG }} \
          echo   "\"config\": {}," >> ${{ env.COMPOSER_CONFIG }} \
          echo   "\"repositories\": {" >> ${{ env.COMPOSER_CONFIG }} \
          echo     "\"metabox.io\": {" >> ${{ env.COMPOSER_CONFIG }} \
          echo       "\"type\": \"composer\",">> ${{ env.COMPOSER_CONFIG }} \
          echo       "\"url\": \"https://packages.metabox.io/${{ secrets.METABOX_API_KEY }}\"" >> ${{ env.COMPOSER_CONFIG }} \
          echo     "}" >> ${{ env.COMPOSER_CONFIG }} \
          echo   "}">> ${{ env.COMPOSER_CONFIG }} \
          echo "}" >> ${{ env.COMPOSER_CONFIG }}

      - name: Update dependencies
        uses: php-actions/composer@v6
        env:
          COMPOSER_HOME: $GITHUB_WORKSPACE
        with:
          command: update
          php_version: 7.4

      - name: Remove config.json file
        run: rm -f $GITHUB_WORKSPACE/config.json

      - name: Pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "main"
          destination_branch: "stage"
          pr_title: "Update dependencies"
          pr_body: "An automated update of WordPress core, plugins and/or PHP dependencies."
          pr_label: "auto-update"
#          pr_reviewer: "wei,worker"
#          pr_assignee: "wei,worker"
          github_token: ${{ secrets.GITHUB_TOKEN }}
