name: Update Dependencies at 06:00 on every 15th day-of-month.

on:
  schedule:
    - cron: "0 6 */15 * *"
  push:
    branches:
      - feature/update_automation

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php_version: 7.4

      - name: Config Composer
        run: composer config repositories.metabox\.io composer 'https://packages.metabox.io/${{ secrets.METABOX_API_KEY }}' --global

      - name: Update dependencies
        run: composer update --no-progress --prefer-dist --optimize-autoloader
#        uses: php-actions/composer@v6
#        env:
#          COMPOSER_HOME: $GITHUB_WORKSPACE
#        with:
#          command: update
#          php_version: 7.4

      - name: Remove config.json file
        run: rm -f $HOME/.composer/config.json

      - name: Pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "main"
          destination_branch: "stage"
          pr_title: "Update dependencies"
          pr_body: "An automated update of WordPress core, plugins and/or PHP dependencies."
          pr_label: "auto-update"
#          pr_reviewer: "wei,worker"
#          pr_assignee: "wei,worker"
          github_token: ${{ secrets.GITHUB_TOKEN }}
