name: Update Dependencies at 06:00 on every 15th day-of-month.

on:
  schedule:
    - cron: "0 6 */15 * *"
  workflow_dispatch:

env:
  COMPOSER_HOME: $HOME/.composer
  COMPOSER_GLOBAL_CONFIG: $COMPOSER_HOME/config.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Config Composer
        run: |
          mkdir -p $COMPOSER_HOME
          echo "{" > $COMPOSER_GLOBAL_CONFIG \
          echo   "\"config\": {}," >> $COMPOSER_GLOBAL_CONFIG \
          echo   "\"repositories\": {" >> $COMPOSER_GLOBAL_CONFIG \
          echo     "\"metabox.io\": {" >> $COMPOSER_GLOBAL_CONFIG \
          echo       "\"type\": \"composer\",">> $COMPOSER_GLOBAL_CONFIG \
          echo       "\"url\": \"https://packages.metabox.io/${{ secrets.METABOX_API_KEY }}\"" >> $COMPOSER_GLOBAL_CONFIG \
          echo     "}" >> $COMPOSER_GLOBAL_CONFIG \
          echo   "}">> $COMPOSER_GLOBAL_CONFIG \
          echo "}" >> $COMPOSER_GLOBAL_CONFIG

      - name: Update dependencies
        uses: php-actions/composer@v6
        with:
          command: update
          php_version: 7.4

      - name: Remove config.json file
        run: rm -f $HOME/config.json

      - name: Pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "main"
          destination_branch: "stage"
          pr_title: "Update dependencies"
          pr_body: "An automated update of WordPress core, plugins and/or PHP dependencies."
          pr_label: "auto-update"
#          pr_reviewer: "wei,worker"
#          pr_assignee: "wei,worker"
          github_token: ${{ secrets.GITHUB_TOKEN }}
